config/routes.rb
Smith::Application.routes.draw do

  resources :posts
  match '/twitter/' => 'posts#twitter' 
  match '/paleo/' => 'posts#paleo', :as => "paleo"
  match '/me/' => 'posts#me'
  match '/work/' => 'posts#work'
  match '/pictures' => 'posts#pictures'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  resources :sessions

  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :tags
  default_scope :order => 'created_at DESC'

  acts_as_taggable 
  #acts_as_taggable_on :location, :who

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :check_user, :only => [:new, :update, :edit, :destroy]

  # GET /posts
  # GET /posts.xml
  def index
    if params[:all]
      @posts = Post.all
    elsif
      @posts = Post.tagged_with("blog")
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  def pictures
    FlickRaw.api_key="cca4e5c768a106ef85d2a19e22f8222d"
    FlickRaw.shared_secret="8a7e63e250a887fe"
    #info = flickr.photos.getInfo(:photo_id => "5752508461")
    #url = FlickRaw.url_photostream(info) # => "http://www.flickr.com/photos/41650587@N02/"
    #logger.info(url)
    username = "dds1024"
    user = flickr.people.findByUsername( :username => username )
    begin
      @photo_list = flickr.people.getPublicPhotos( :user_id => user.nsid, :per_page => 12, :extras => 'description' )

      @photo_list.each do |p|
        sizes = flickr.photos.getSizes :photo_id => p.id
        #logger.info(sizes.inspect)
        #original = sizes.find {|s| s.label == 'Original' }
        #original.width       # => "800"
        #logger.info(p.inspect)
      end
    rescue
      @photo_list = []
      flash[:notice]="Something happend with Flickr's API, try refreshing to fix."
      #logger.info(@photo_list)
      #@posts = Post.tagged_with("me")
    end
      respond_to do |format|
        format.html
      end
    end

  def me
    @posts = Post.tagged_with("me")
    respond_to do |format|
      format.html
    end
  end

  def work
    @posts = Post.tagged_with("work")
    respond_to do |format|
      format.html
    end
  end

  def twitter
    respond_to do |format|
      format.html
    end
  end

  def paleo
    Twitter.configure do |config|
      config.consumer_key = 'WOBXTuBXu94Z8gnJ2lw'
      config.consumer_secret = 'm0zk3JSuVGeMqhfAKh9FTS11VsYkZ5vinHWuJJCfo'
      config.oauth_token = '448955415-krkAltBKcSB7oSZorfDGN7oautktopEQmlxMJzXj'
      config.oauth_token_secret = '4pLdwBKyvgVwNmF4hF1b4oQrYODohdIFuBB3rweg'
    end
    #@tweets = Twitter.search("to:paleofoodfight", :rpp => 100, :include_entities => true)
    if params[:count]
      @tweets = Twitter.mentions(:count => params[:count])
    else
      @tweets = Twitter.mentions(:count => 20)
    end
    @pics = []
    @tweets.each do |tweet, k|
      t = Twitter.status(tweet.id, :include_entities => true)
      if t.attrs['entities']['media']
        image_url = t.attrs['entities']['media'][0]['media_url']
      elsif t.attrs['entities']['urls'] and not t.attrs['entities']['urls'].empty?
        image_url = t.attrs['entities']['urls'][0]['expanded_url'] + ':iphone'
      else
        next
      end
      
      if image_url
        text = tweet.text.sub('@PaleoFoodFight', '')
        regex = Regexp.new '((https?:\/\/|www\.)([-\w\.]+)+(:\d+)?(\/([\w\/_\.]*(\?\S+)?)?)?)'
        text = text.gsub( regex, '' )
        @pics << { :image_url => image_url, :text => text, :user => tweet.attrs['user']['name']}
      end
      image_url = nil
       
    end
    if not params[:blog]
      render :template => 'posts/paleo_squares.html.erb'
    else
      respond_to do |format|
        format.html
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
      @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])
    @post.tag_list = params[:tags]

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])
    @post.tag_list = params[:tags]
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end

  private 

    def check_user
      if !current_user
        flash[:error] = "Sorry, you don't have permission to manage posts!"
        redirect_to(root_url)                                                    
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <title>Dustin Smith</title>
  <%= stylesheet_link_tag :all %>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="initial-scale:1.0, width=device-width" />
  <meta name="Description" content="Dustin Smith's Personal Website. Web developer discussing Rails, Python, Node.js, UX, and anything else that comes up in life." />
  <meta name="Author" content="Dustin Smith" />
  <meta name="keywords" content="web,html,css,javascript,nodejs,rails,ruby,dustin,smith,dustinsmith1024,python" />
</head>
<body>
  <div id="header">
    <h1><a href="/">Dustin Smith</a></h1>
    <p></p>
  </div>
  <div id="nav">
    <ul>
      <li id="blog"><a href="/">Blog</a></li>
      <li id="me"><a href="/me">Me</a></li>
      <li id="work"><a href="/work">Work</a></li>
      <li id="pics"><a href="/pictures">Pictures</a></li>
      <li id="twitter"><a href="/twitter"><img src="/images/twitter_bird_blue.png" alt="Twitter Link [Icon]" class="twitter-bird" /></a></li>
      <li id="email"><a href="mailto:dds1024@gmail.com"><img src="/images/email.png" alt="Email Link [Icon]" class="email-link" /></a></li>
    </ul>
  </div>
  <div id="body">
    <div class="flash-container">
      <% flash.each do |key, value| %>
          <p class="flash <%= key %>"><%= value %></p>
        <% end %>
    </div>
    <% if current_user %>
      <div id="user_nav" class="post">
        Logged in as <%= current_user.email %>.
        <%= link_to "Log out", log_out_path %> | 
	<%= link_to "New Post", new_post_path %>
      </div>
    <% end %>
    <%= yield %>
  </div>
  <div id="footer" >
  </div>
  <div id="deactivate" class="hidden" ></div>
  <div id="popup" class="hidden" ></div>
  <script>
  /*  var myTweetsFixer = function (twitters) {
      var i, newTweets = [];
      for (i = 0; i < twitters.length; i++) {
        if (/smith1024/.test(twitters[i].text)) {
          twitters[i].text = '<span class="status">Current Status: </span>' + twitters[i].text
          newTweets.push(twitters[i]);
        }
      }
      twitterCallback2(newTweets);
    };*/
  </script>
  <%= javascript_include_tag "jquery.min.js", "jquery_ujs.js", "jquery.lightbox.js", "application" %>
  <!--[if lt IE 9]>
    <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js">IE7_PNG_SUFFIX=".png";</script>
  <![endif]-->
  <%= csrf_meta_tag %>
  <script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <% @post.body = '<p class="intro"><span class="first-letter">W</span>elcome.</p><p>Next P</p>' if @post.body.blank? %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class=field">
    <%= f.label :tags %>
    <input type="text" id="tags" name="tags" value="<%= @post.tags.join(',') %>" />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post" >
  <h2><%= link_to post.title, post %></h2>
  <p><%= post.updated_at.to_s(:long) %></p>
  <div><%= raw(post.body) %></div>
  <p>Tagged with: <%= post.tags.to_sentence %></p>
  <%#
  <p>
    <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="dustinsmith1024">Tweet</a>
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
  </p>
  %>
  <p class="footer"> 
  <% if current_user %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete if current_user %>
  <% end %>
  </p>
</div>

app/views/posts/edit.html.erb
<div class="post">
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div id="posts" >
  <%= render @posts %>
</div>

<%= link_to 'New Post', new_post_path if current_user %>

app/views/posts/me.html.erb
<div id="posts" >
  <%= render @posts %>
</div>

<%= link_to 'New Post', new_post_path if current_user %>

app/views/posts/new.html.erb
<div class="post">
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/pictures.html.erb
<div class="post">
<h2>
  <a href="http://www.flickr.com/photos/dustinsmith1024/">My Flickr Photostream</a>
</h2>
<p>
  Here's some pictures from my Flickr account.
  Click the photo for a pop-up image.
  Click the blue titles for full size image.
</p>
<div class="center">
<% @photo_list.each do |photo| %>
  <p class="photo">
    <% info = flickr.photos.getInfo(:photo_id => photo.id) %>
    <% img_url = FlickRaw.url_m(info) %><%# change _b to _s _m _whatev for different sizes %>
    <% big_img_url = FlickRaw.url_b(info) %>
    <a class="lightbox" rel="my-pics" href="<%= big_img_url %>" title="<%= photo.title %>: <%= photo.description %>">
      <img src="<%= img_url %>" alt="Flickr Photo" title="<%= photo.title %>" />
    </a>
    <br/>
    <span class="caption" >
      <a href="<%= big_img_url %>" >
        <%= photo.title %>
      </a>
    </span>
  </p>
<% end %>
</div>
<div id="clear">&nbsp;</div>
</div>

app/views/posts/show.html.erb
<div id="posts" >
  <%= render @post %>
</div>

<p class="content-links">
  <%= link_to 'Back', posts_path %>
</p>

app/views/posts/twitter.html.erb
<div class="twitter-page">
<h2>My <img src="images/twitter-blue.png" class="twitter-link" /> Posts</h2>
<p>Follow me <a href="http://twitter.com/#!/dds1024">@dds1024</a>.</p>
<div id="twitter_div">
  <ul id="twitter_update_list">
    <li>&nbsp;</li>
  </ul>
</div>

<script type="text/javascript" src="http://twitter.com/javascripts/blogger.js"></script>
<script type="text/javascript" src="http://twitter.com/statuses/user_timeline/dds1024.json?callback=twitterCallback2&count=20"></script>
</div>

app/views/posts/work.html.erb
<div id="posts" >
  <%= render @posts %>
</div>

<%= link_to 'New Post', new_post_path if current_user %>